// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtL560v4BFTFBWtSqVqURFmkzj7_i6Ko',
    appId: '1:1001244906217:web:6e75e62cf5318ad7539678',
    messagingSenderId: '1001244906217',
    projectId: 'yapper-chat-application',
    authDomain: 'yapper-chat-application.firebaseapp.com',
    storageBucket: 'yapper-chat-application.firebasestorage.app',
    measurementId: 'G-SG83WR04ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGBQlNJT3hLaYAjpZBv7B9SrBV1vzPlow',
    appId: '1:1001244906217:android:d13dc53dfa88e919539678',
    messagingSenderId: '1001244906217',
    projectId: 'yapper-chat-application',
    storageBucket: 'yapper-chat-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjdTTJ_71zbrii3DFo5AgmosUSSzvAvc',
    appId: '1:1001244906217:ios:a686eb40c60601e0539678',
    messagingSenderId: '1001244906217',
    projectId: 'yapper-chat-application',
    storageBucket: 'yapper-chat-application.firebasestorage.app',
    iosClientId: '1001244906217-p4ug395555a8fjco01iflre5djt8flom.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjdTTJ_71zbrii3DFo5AgmosUSSzvAvc',
    appId: '1:1001244906217:ios:a686eb40c60601e0539678',
    messagingSenderId: '1001244906217',
    projectId: 'yapper-chat-application',
    storageBucket: 'yapper-chat-application.firebasestorage.app',
    iosClientId: '1001244906217-p4ug395555a8fjco01iflre5djt8flom.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLtL560v4BFTFBWtSqVqURFmkzj7_i6Ko',
    appId: '1:1001244906217:web:fbe403be1923c051539678',
    messagingSenderId: '1001244906217',
    projectId: 'yapper-chat-application',
    authDomain: 'yapper-chat-application.firebaseapp.com',
    storageBucket: 'yapper-chat-application.firebasestorage.app',
    measurementId: 'G-REP9L2QZB5',
  );

}